# Generated by Django 4.2.3 on 2023-07-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socialnetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('phone', models.CharField(max_length=255, verbose_name='Тел.номер')),
                ('google', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('locate', models.CharField(max_length=255, verbose_name='Адрес')),
                ('message', models.TextField(max_length=255, verbose_name='Введите ваше сообщение')),
                ('twitter', models.URLField(verbose_name='Ссылка на twiter')),
                ('facebook', models.URLField(verbose_name='Ссылка на Facebook')),
                ('linkedin', models.URLField(verbose_name='Ссылка на linkedin')),
                ('youtube', models.URLField(verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': 'Настройки контактов',
                'verbose_name_plural': 'Настройка контактов',
            },
        ),
    ]
