# Generated by Django 4.2.3 on 2023-07-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='subject',
            field=models.TextField(default=1, max_length=255, verbose_name='Тема сообщения'),
            preserve_default=False,
        ),
    ]
