# Generated by Django 4.2.3 on 2023-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_google_socialnetworks_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема сообщения'),
        ),
    ]
