# Generated by Django 4.2.3 on 2023-07-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=150, verbose_name='Название сайта')),
                ('logo_site', models.ImageField(upload_to='logo/', verbose_name='Логотип сайта')),
                ('info_site', models.CharField(max_length=255, verbose_name='Дополнительная информация о сайте')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
