# Generated by Django 4.2.3 on 2023-07-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doom', models.CharField(max_length=150, verbose_name='Название иконок на главной странице')),
            ],
            options={
                'verbose_name': 'Настройка домой',
                'verbose_name_plural': 'Настройки домой',
            },
        ),
    ]
