# Generated by Django 4.2.3 on 2023-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doom',
        ),
        migrations.AddField(
            model_name='settings',
            name='name_doom',
            field=models.CharField(default=1, max_length=150, verbose_name='Название иконок на главной странице'),
            preserve_default=False,
        ),
    ]
