# Generated by Django 4.2.3 on 2023-07-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_doom_settings_name_doom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='name_doom',
        ),
    ]
