# Generated by Django 4.2.3 on 2023-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doom'),
    ]

    operations = [
        migrations.AddField(
            model_name='doom',
            name='name_doom2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doom',
            name='name_doom3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doom',
            name='name_doom',
            field=models.CharField(max_length=50, verbose_name='Название иконок на главной странице'),
        ),
    ]
