# Generated by Django 4.2.3 on 2023-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_doom_name_doom2_doom_name_doom3_alter_doom_name_doom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialnetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Тел.номер')),
                ('google', models.EmailField(max_length=254, verbose_name='Почта')),
                ('locate', models.CharField(max_length=255, verbose_name='Адрес')),
                ('twitter', models.URLField(verbose_name='Ссылка на twiter')),
                ('facebook', models.URLField(verbose_name='Ссылка на Facebook')),
                ('linkedin', models.URLField(verbose_name='Ссылка на linkedin')),
                ('youtube', models.URLField(verbose_name='Ссылка на Youtube')),
            ],
            options={
                'verbose_name': 'Настройки соц.сетей',
                'verbose_name_plural': 'Настройка соц.сетей',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={},
        ),
        migrations.AlterField(
            model_name='doom',
            name='name_doom',
            field=models.CharField(max_length=50, verbose_name='Слайд №1'),
        ),
        migrations.AlterField(
            model_name='doom',
            name='name_doom2',
            field=models.CharField(max_length=50, verbose_name='Слайд №2'),
        ),
        migrations.AlterField(
            model_name='doom',
            name='name_doom3',
            field=models.CharField(max_length=50, verbose_name='Слайд №3'),
        ),
    ]
