# Generated by Django 4.2.3 on 2023-07-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_socialnetworks_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройка сайта'},
        ),
    ]
